/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2023-11-26 16:15:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/final_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DemoProj/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/jsf_core.tld", Long.valueOf(1479140578000L));
    _jspx_dependants.put("jar:file:/D:/final_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DemoProj/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/html_basic.tld", Long.valueOf(1479140598000L));
    _jspx_dependants.put("/WEB-INF/lib/jsf-impl-2.2.14.jar", Long.valueOf(1696481128221L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:view
    com.sun.faces.taglib.jsf_core.ViewTag _jspx_th_f_005fview_005f0 = new com.sun.faces.taglib.jsf_core.ViewTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fview_005f0);
    try {
      _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fview_005f0.setParent(null);
      _jspx_th_f_005fview_005f0.setJspId("jsp_2144333035_0");
      int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fview_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("<title>JSP Page</title>\r\n");
          out.write("<!-- Meta Tags -->\r\n");
          out.write("<meta charset=\"utf-8\">\r\n");
          out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
          out.write("<meta name=\"keywords\" content=\"Site keywords here\">\r\n");
          out.write("<meta name=\"description\" content=\"\">\r\n");
          out.write("<meta name='copyright' content=''>\r\n");
          out.write("<meta name=\"viewport\"\r\n");
          out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
          out.write("\r\n");
          out.write("<!-- Title -->\r\n");
          out.write("<title>Mediplus - Free Medical and Doctor Directory HTML\r\n");
          out.write("\tTemplate.</title>\r\n");
          out.write("\r\n");
          out.write("<!-- Favicon -->\r\n");
          out.write("<link rel=\"icon\" href=\"img/favicon.png\">\r\n");
          out.write("\r\n");
          out.write("<!-- Google Fonts -->\r\n");
          out.write("<link\r\n");
          out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap\"\r\n");
          out.write("\trel=\"stylesheet\">\r\n");
          out.write("\r\n");
          out.write("<!-- Bootstrap CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
          out.write("<!-- Nice Select CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/nice-select.css\">\r\n");
          out.write("<!-- Font Awesome CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
          out.write("<!-- icofont CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/icofont.css\">\r\n");
          out.write("<!-- Slicknav -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/slicknav.min.css\">\r\n");
          out.write("<!-- Owl Carousel CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/owl-carousel.css\">\r\n");
          out.write("<!-- Datepicker CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/datepicker.css\">\r\n");
          out.write("<!-- Animate CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/animate.min.css\">\r\n");
          out.write("<!-- Magnific Popup CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
          out.write("\r\n");
          out.write("<!-- Medipro CSS -->\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/normalize.css\">\r\n");
          out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
          out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("\t<!-- Preloader -->\r\n");
          out.write("\t<div class=\"preloader\">\r\n");
          out.write("\t\t<div class=\"loader\">\r\n");
          out.write("\t\t\t<div class=\"loader-outter\"></div>\r\n");
          out.write("\t\t\t<div class=\"loader-inner\"></div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t<div class=\"indicator\">\r\n");
          out.write("\t\t\t\t<svg width=\"16px\" height=\"12px\">\r\n");
          out.write("                        <polyline id=\"back\"\r\n");
          out.write("\t\t\t\t\t\tpoints=\"1 6 4 6 6 11 10 1 12 6 15 6\"></polyline>\r\n");
          out.write("                        <polyline id=\"front\"\r\n");
          out.write("\t\t\t\t\t\tpoints=\"1 6 4 6 6 11 10 1 12 6 15 6\"></polyline>\r\n");
          out.write("                    </svg>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\t<!-- End Preloader -->\r\n");
          out.write("\r\n");
          out.write("\t<!-- Get Pro Button -->\r\n");
          out.write("\t<ul class=\"pro-features\">\r\n");
          out.write("\t\t<a class=\"get-pro\" href=\"#\">Get Pro</a>\r\n");
          out.write("\t\t<li class=\"big-title\">Pro Version Available on Themeforest</li>\r\n");
          out.write("\t\t<li class=\"title\">Pro Version Features</li>\r\n");
          out.write("\t\t<li>2+ premade home pages</li>\r\n");
          out.write("\t\t<li>20+ html pages</li>\r\n");
          out.write("\t\t<li>Color Plate With 12+ Colors</li>\r\n");
          out.write("\t\t<li>Sticky Header / Sticky Filters</li>\r\n");
          out.write("\t\t<li>Working Contact Form With Google Map</li>\r\n");
          out.write("\t\t<div class=\"button\">\r\n");
          out.write("\t\t\t<a\r\n");
          out.write("\t\t\t\thref=\"http://preview.themeforest.net/item/mediplus-medical-and-doctor-html-template/full_screen_preview/26665910?_ga=2.145092285.888558928.1591971968-344530658.1588061879\"\r\n");
          out.write("\t\t\t\ttarget=\"_blank\" class=\"btn\">Pro Version Demo</a> <a\r\n");
          out.write("\t\t\t\thref=\"https://themeforest.net/item/mediplus-medical-and-doctor-html-template/26665910\"\r\n");
          out.write("\t\t\t\ttarget=\"_blank\" class=\"btn\">Buy Pro Version</a>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</ul>\r\n");
          out.write("\r\n");
          out.write("\t<!-- Header Area -->\r\n");
          out.write("\t<header class=\"header\">\r\n");
          out.write("\t\t<!-- Topbar -->\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t<!-- End Topbar -->\r\n");
          out.write("\t\t<!-- Header Inner -->\r\n");
          out.write("\t\t<div class=\"header-inner\">\r\n");
          out.write("\t\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t\t<div class=\"inner\">\r\n");
          out.write("\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-12\">\r\n");
          out.write("\t\t\t\t\t\t\t<!-- Start Logo -->\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"logo\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<a href=\"index.html\"><img src=\"img/logo.png\" alt=\"#\"></a>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<!-- End Logo -->\r\n");
          out.write("\t\t\t\t\t\t\t<!-- Mobile Nav -->\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"mobile-nav\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t<!-- End Mobile Nav -->\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-7 col-md-9 col-12\">\r\n");
          out.write("\t\t\t\t\t\t\t<!-- Main Menu -->\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"main-menu\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<nav class=\"navigation\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav menu\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">Home <i\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icofont-rounded-down\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home Page 1</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Doctos </a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Services </a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Pages <i class=\"icofont-rounded-down\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"404.html\">404 Error</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Blogs <i class=\"icofont-rounded-down\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">Blog Details</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact Us</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t</nav>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<!--/ End Main Menu -->\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-2 col-12\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"get-quote\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<a href=\"appointment.html\" class=\"btn\">Book Appointment</a>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t\t<!--/ End Header Inner -->\r\n");
          out.write("\t</header>\r\n");
          out.write("\t<!-- End Header Area -->\r\n");
          out.write("\r\n");
          out.write("\t<!-- Slider Area -->\r\n");
          out.write("\t<section class=\"slider\">\r\n");
          out.write("\t\t<div class=\"hero-slider\">\r\n");
          out.write("\t\t\t<!-- Start Single Slider -->\r\n");
          out.write("\t\t\t<div class=\"single-slider\"\r\n");
          out.write("\t\t\t\tstyle=\"background-image: url('img/slider2.jpg')\">\r\n");
          out.write("\t\t\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-7\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t\tWe Provide <span>Medical</span> Services That You Can <span>Trust!</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
          out.write("\t\t\t\t\t\t\t\t\tMauris sed nisl pellentesque, faucibus libero eu, gravida quam.\r\n");
          out.write("\t\t\t\t\t\t\t\t</p>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"button\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn\">Get Appointment</a> <a href=\"#\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn primary\">Learn More</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<!-- End Single Slider -->\r\n");
          out.write("\t\t\t<!-- Start Single Slider -->\r\n");
          out.write("\t\t\t<div class=\"single-slider\"\r\n");
          out.write("\t\t\t\tstyle=\"background-image: url('img/slider.jpg')\">\r\n");
          out.write("\t\t\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-7\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t\tWe Provide <span>Medical</span> Services That You Can <span>Trust!</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
          out.write("\t\t\t\t\t\t\t\t\tMauris sed nisl pellentesque, faucibus libero eu, gravida quam.\r\n");
          out.write("\t\t\t\t\t\t\t\t</p>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"button\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn\">Get Appointment</a> <a href=\"#\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn primary\">About Us</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<!-- Start End Slider -->\r\n");
          out.write("\t\t\t<!-- Start Single Slider -->\r\n");
          out.write("\t\t\t<div class=\"single-slider\"\r\n");
          out.write("\t\t\t\tstyle=\"background-image: url('img/slider3.jpg')\">\r\n");
          out.write("\t\t\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-lg-7\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t\tWe Provide <span>Medical</span> Services That You Can <span>Trust!</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t</h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n");
          out.write("\t\t\t\t\t\t\t\t\tMauris sed nisl pellentesque, faucibus libero eu, gravida quam.\r\n");
          out.write("\t\t\t\t\t\t\t\t</p>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"button\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn\">Get Appointment</a> <a href=\"#\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn primary\">Conatct Now</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<!-- End Single Slider -->\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</section>\r\n");
          out.write("\t<!--/ End Slider Area -->\r\n");
          out.write("\r\n");
          out.write("\t<!-- Start Schedule Area -->\r\n");
          out.write("\t<section class=\"schedule\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"schedule-inner\">\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 col-12 \">\r\n");
          out.write("\t\t\t\t\t\t<!-- single-schedule -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"single-schedule first\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"inner\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-ambulance\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"single-content\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>Lorem Amet</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<h4>Emergency Cases</h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<p>Lorem ipsum sit amet consectetur adipiscing elit.\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tVivamus et erat in lacus convallis sodales.</p>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">LEARN MORE<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 col-12\">\r\n");
          out.write("\t\t\t\t\t\t<!-- single-schedule -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"single-schedule middle\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"inner\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<i class=\"icofont-prescription\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"single-content\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>Fusce Porttitor</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<h4>Doctors Timetable</h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<p>Lorem ipsum sit amet consectetur adipiscing elit.\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tVivamus et erat in lacus convallis sodales.</p>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">LEARN MORE<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-12 col-12\">\r\n");
          out.write("\t\t\t\t\t\t<!-- single-schedule -->\r\n");
          out.write("\t\t\t\t\t\t<div class=\"single-schedule last\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"inner\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<i class=\"icofont-ui-clock\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"single-content\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<span>Donec luctus</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<h4>Opening Hours</h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<ul class=\"time-sidual\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"day\">Monday - Fridayp <span>8.00-20.00</span></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"day\">Saturday <span>9.00-18.30</span></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"day\">Monday - Thusday <span>9.00-15.00</span></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">LEARN MORE<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</section>\r\n");
          out.write("\t<!--/End Start schedule Area -->\r\n");
          out.write("\r\n");
          out.write("\t<!-- Start Feautes -->\r\n");
          out.write("\t<section class=\"Feautes section\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
          out.write("\t\t\t\t\t<div class=\"section-title\">\r\n");
          out.write("\t\t\t\t\t\t<h2>We Are Always Ready to Help You & Your Family</h2>\r\n");
          out.write("\t\t\t\t\t\t<img src=\"img/section-img.png\" alt=\"#\">\r\n");
          out.write("\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet consectetur adipiscing elit\r\n");
          out.write("\t\t\t\t\t\t\tpraesent aliquet. pretiumts</p>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t<div class=\"col-lg-4 col-12\">\r\n");
          out.write("\t\t\t\t\t<!-- Start Single features -->\r\n");
          out.write("\t\t\t\t\t<div class=\"single-features\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"signle-icon\">\r\n");
          out.write("\t\t\t\t\t\t\t<i class=\"icofont icofont-ambulance-cross\"></i>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<h3>Emergency Help</h3>\r\n");
          out.write("\t\t\t\t\t\t<p>Lorem ipsum sit, consectetur adipiscing elit. Maecenas mi\r\n");
          out.write("\t\t\t\t\t\t\tquam vulputate.</p>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<!-- End Single features -->\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"col-lg-4 col-12\">\r\n");
          out.write("\t\t\t\t\t<!-- Start Single features -->\r\n");
          out.write("\t\t\t\t\t<div class=\"single-features\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"signle-icon\">\r\n");
          out.write("\t\t\t\t\t\t\t<i class=\"icofont icofont-medical-sign-alt\"></i>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<h3>Enriched Pharmecy</h3>\r\n");
          out.write("\t\t\t\t\t\t<p>Lorem ipsum sit, consectetur adipiscing elit. Maecenas mi\r\n");
          out.write("\t\t\t\t\t\t\tquam vulputate.</p>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<!-- End Single features -->\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"col-lg-4 col-12\">\r\n");
          out.write("\t\t\t\t\t<!-- Start Single features -->\r\n");
          out.write("\t\t\t\t\t<div class=\"single-features last\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"signle-icon\">\r\n");
          out.write("\t\t\t\t\t\t\t<i class=\"icofont icofont-stethoscope\"></i>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<h3>Medical Treatment</h3>\r\n");
          out.write("\t\t\t\t\t\t<p>Lorem ipsum sit, consectetur adipiscing elit. Maecenas mi\r\n");
          out.write("\t\t\t\t\t\t\tquam vulputate.</p>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<!-- End Single features -->\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</section>\r\n");
          out.write("\t<!--/ End Feautes -->\r\n");
          out.write("\r\n");
          out.write("\t<!-- Start Fun-facts -->\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t<!--/ End Copyright -->\r\n");
          out.write("\t</footer>\r\n");
          out.write("\t<!--/ End Footer Area -->\r\n");
          out.write("\r\n");
          out.write("\t<!-- jquery Min JS -->\r\n");
          out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
          out.write("\t<!-- jquery Migrate JS -->\r\n");
          out.write("\t<script src=\"js/jquery-migrate-3.0.0.js\"></script>\r\n");
          out.write("\t<!-- jquery Ui JS -->\r\n");
          out.write("\t<script src=\"js/jquery-ui.min.js\"></script>\r\n");
          out.write("\t<!-- Easing JS -->\r\n");
          out.write("\t<script src=\"js/easing.js\"></script>\r\n");
          out.write("\t<!-- Color JS -->\r\n");
          out.write("\t<script src=\"js/colors.js\"></script>\r\n");
          out.write("\t<!-- Popper JS -->\r\n");
          out.write("\t<script src=\"js/popper.min.js\"></script>\r\n");
          out.write("\t<!-- Bootstrap Datepicker JS -->\r\n");
          out.write("\t<script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
          out.write("\t<!-- Jquery Nav JS -->\r\n");
          out.write("\t<script src=\"js/jquery.nav.js\"></script>\r\n");
          out.write("\t<!-- Slicknav JS -->\r\n");
          out.write("\t<script src=\"js/slicknav.min.js\"></script>\r\n");
          out.write("\t<!-- ScrollUp JS -->\r\n");
          out.write("\t<script src=\"js/jquery.scrollUp.min.js\"></script>\r\n");
          out.write("\t<!-- Niceselect JS -->\r\n");
          out.write("\t<script src=\"js/niceselect.js\"></script>\r\n");
          out.write("\t<!-- Tilt Jquery JS -->\r\n");
          out.write("\t<script src=\"js/tilt.jquery.min.js\"></script>\r\n");
          out.write("\t<!-- Owl Carousel JS -->\r\n");
          out.write("\t<script src=\"js/owl-carousel.js\"></script>\r\n");
          out.write("\t<!-- counterup JS -->\r\n");
          out.write("\t<script src=\"js/jquery.counterup.min.js\"></script>\r\n");
          out.write("\t<!-- Steller JS -->\r\n");
          out.write("\t<script src=\"js/steller.js\"></script>\r\n");
          out.write("\t<!-- Wow JS -->\r\n");
          out.write("\t<script src=\"js/wow.min.js\"></script>\r\n");
          out.write("\t<!-- Magnific Popup JS -->\r\n");
          out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
          out.write("\t<!-- Counter Up CDN JS -->\r\n");
          out.write("\t<script\r\n");
          out.write("\t\tsrc=\"http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js\"></script>\r\n");
          out.write("\t<!-- Bootstrap JS -->\r\n");
          out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
          out.write("\t<!-- Main JS -->\r\n");
          out.write("\t<script src=\"js/main.js\"></script>\r\n");
          out.write("\r\n");
          out.write("</body>\r\n");
          out.write("\t</html>\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fview_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }
}
